#!/bin/sh

case "$1" in
  start)
    echo -n "Starting ep-control: "
    mkdir -p /tmp/ep-control/dhcpc
    currPartition=$(bootcfg i)
    /usr/bin/wrapper -d -s $((1<<24)) -W $((1<<19)) -E $((1<<19)) -f /var/log/ep-control.log -w '---report to cloud---:' -r $numRestart -- /usr/sbin/ep-control -pprof-port 2000 -new-dhcpc -partition $currPartition
    echo OK
    ;;
  stop)
    echo -n "Stopping ep-control: "
    start-stop-daemon -K -x /usr/sbin/ep-control
    echo OK
    ;;
  restart)
    $0 stop
    . maxNumRestarts
    $0 start
    ;;
  *)
    echo "Usage: $0 (start|stop|restart)"
    exit 1
esac

exit $?

